apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"test-container:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"test-container\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: test-container
      app.kubernetes.io/component: test-container
      app.kubernetes.io/instance: test-container
    name: test-container
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: test-container
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: test-container
      spec:
        containers:
        - image: ' '
          name: test-container
          resources: {}
  status: {}
kind: List
metadata: {}