apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"test-container:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"test-container\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2023-07-10T07:33:39Z"
  generation: 2
  labels:
    app: test-container
    app.kubernetes.io/component: test-container
    app.kubernetes.io/instance: test-container
  name: test-container
  namespace: enet-thihathura-dev
  resourceVersion: "932540964"
  uid: c23df0f7-81e9-41cb-9810-631419010f99
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: test-container
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: test-container
    spec:
      containers:
      - image: thihathura/test-container@sha256:43fe887cec37f0dc5492ce7e27b5ea25f86b29b1eb5517de71a1ad9142b7ecbe
        imagePullPolicy: IfNotPresent
        name: test-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/test-data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: blog-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-07-10T07:33:40Z"
    lastUpdateTime: "2023-07-10T07:33:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-07-10T07:33:39Z"
    lastUpdateTime: "2023-07-10T07:33:40Z"
    message: ReplicaSet "test-container-7c9b46885d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: blog-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}